Repository jenkinsci/mailer-plugin, pull requests merged in 2019-09, with the labels that each got.

#60 [JENKINS-58768] Fix send test mail after adding JCasC compatibility
  src/main/java/hudson/tasks/Mailer.java
  src/main/resources/hudson/tasks/Mailer/global.jelly
Labels: bug

#62 [JENKINS-59172] - Use GitHub as a source of the plugin's documentation on plugins.jenkins.io
  pom.xml
Labels: documentation

#37 [JENKINS-25089] Add Auto-Submitted header to emails (RFC 3834)
  src/main/java/hudson/tasks/MailSender.java
Labels: enhancement

#33 [JENKINS-39976] Add line break before separator line even if there are no changesets found
  src/main/java/hudson/tasks/MailSender.java
Labels: bug

#63 Fix changelog version reference
  README.adoc
Labels: documentation
