Repository jenkinsci/mailer-plugin, pull requests merged in 2019-07, with the labels that each got.

#56 Enable Release Drafter for the repository
  .github/release-drafter.yml
Labels: internal

#53 Java 11 readiness: build both on JDK8 and JDK11
  Jenkinsfile
  pom.xml
Labels: tests

#57 Enable Dependabot for the repository
  .dependabot/config.yml
Labels: internal

#54 Update JavaMail from 1.4.4 to 1.4.7
  pom.xml
Labels: dependencies

#58 Move documentation from Wiki to GitHub
  README.adoc
  README.md
Labels: documentation
