Repository jenkinsci/mailer-plugin, pull requests merged in 2021-03, with the labels that each got.

#96 Hacktoberfest: Trim white space
  src/main/java/hudson/tasks/Mailer.java
  src/main/java/hudson/tasks/SMTPAuthentication.java
  src/main/resources/hudson/tasks/Mailer/global.jelly
  src/test/java/hudson/tasks/MailerTest.java
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#107 Cleanup getInstance() references
  src/main/java/hudson/tasks/MailSender.java
  src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
Labels: chore

#104 [JENKINS-64629] Fix uncaught exception for unauthorized users
  src/main/java/hudson/tasks/MailSender.java
  src/main/resources/jenkins/plugins/mailer/tasks/i18n/Messages.properties
Labels: bug

#97 [terminology] Removing indian word in French email example.
  src/main/resources/hudson/tasks/Mailer/UserProperty/config_fr.properties
Labels: chore, hacktoberfest-accepted
