Repository jenkinsci/mailer-plugin, pull requests merged in 2022-01, with the labels that each got.

#138 Update deps
  pom.xml
  src/main/java/hudson/tasks/MailSender.java
  src/main/java/hudson/tasks/Mailer.java
  src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
Labels: dependencies

#133 Drop dependency on Commons Codec
  src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
  src/test/java/jenkins/plugins/mailer/tasks/MimeMessageBuilderTest.java
Labels: dependencies

#141 Enable CD
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
  src/main/resources/index.jelly
Labels: chore

#89 Resolve Mailer TODOs & warnings, fixing port data in README
  README.adoc
  src/main/java/hudson/tasks/Mailer.java
  src/main/java/jenkins/plugins/mailer/tasks/MimeMessageBuilder.java
  src/test/java/hudson/tasks/MailerTest.java
  src/test/java/jenkins/plugins/mailer/MailerJCasCCompatibilityTest.java
Labels: documentation

#142 Bump `mock-javamail` from 1.9 to 1.12
  pom.xml
Labels: dependencies
